version: '3'
services:
  es01:
    build: .
    container_name: es01
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - ./org:/usr/share/elasticsearch/config/org
    ports:
      - 9200:9200

volumes:
  esdata01:
    driver: local

